# Generated by Django 5.1.2 on 2024-10-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_read_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='texts', to='fast_read_app.block', verbose_name='Блоки'),
        ),
    ]
