# Generated by Django 5.1.2 on 2024-10-11 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_read_app', '0003_answer_remove_test_quetions_remove_block_tests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='blocks',
        ),
        migrations.AddField(
            model_name='block',
            name='main_text',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='fast_read_app.text', verbose_name='Название текста'),
        ),
        migrations.AddField(
            model_name='block',
            name='no',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер блока'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='block',
            name='text',
            field=models.TextField(verbose_name='Текст блока'),
        ),
        migrations.AlterField(
            model_name='quetions',
            name='answers',
            field=models.ManyToManyField(related_name='tests', to='fast_read_app.answer', verbose_name='Ответы'),
        ),
    ]
