# Generated by Django 5.1.2 on 2024-10-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_read_app', '0004_remove_text_blocks_block_main_text_block_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='test',
            new_name='tests',
        ),
    ]
